version: "3.6"

services:

  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    restart: unless-stopped
    tmpfs:
      # Use tmpfs for pg_stat_tmp to resolve WARNING: could not open statistics
      # file
      # https://stackoverflow.com/questions/66325175/docker-container-with-postgres-warning-could-not-open-statistics-file-pg-stat
      - /var/lib/postgresql/data/pg_stat_tmp
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEV_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=cc_licenses.settings.local
    image: cc_licenses
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/home/cc
      - ../cc-licenses-data:/home/cc-licenses-data

  static:
    image: nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ../cc-licenses-data/config/:/etc/nginx/conf.d:ro
      - ../cc-licenses-data/docs/:/usr/share/nginx/html:ro
