version: "3.2"

services:

  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data/db
        target: /var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/data/pg_stat_tmp

  app:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEV_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=cc_licenses.settings.local
    image: cc_licenses
    ports:
      - "8000:8000"
    volumes:
      - .:/home/cc
      - ../cc-licenses-data:/home/cc-licenses-data

  static:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ../cc-licenses-data/docs/:/usr/share/nginx/html:ro
