# Remember to also update the GitHub Actions configuration, as appropriate:
#   cc-legal-tools-app/.github/workflows/pre-commit.yml
#
# Also see:
#   .env
#   Dockerfile

version: "3.6"

services:

  app:
    build: .
    command: ./manage.py runserver 0.0.0.0:${PORT_APP}
    environment:
      - DJANGO_SETTINGS_MODULE
    ports:
      - "${PORT_APP}:${PORT_APP}"
    restart: always
    volumes:
      - .:/home/cc
      - ${RELPATH_DATA}:/home/cc-legal-tools-data
