[tool.black]
exclude = '''
(
  /node_modules/
  | /venv/
)
'''
line-length = 88
target_version = ['py37']


[tool.coverage.run]
branch = true
omit = [
    '*/management/commands/*',
    '*/migrations/*',
    '*/settings/*',
    '*/tests/*',
    '*/urls.py',
    '*/wsgi.py',
    '.direnv/*',
    'env/*',
    'fabfile.py',
    'manage.py',
    'venv/*',
]
source = [
    '.',
]

[tool.coverage.report]
show_missing = true
skip_covered = true


# [tool.flake8]
#   config: .flake8
# also see: https://gitlab.com/pycqa/flake8/-/issues/428


[tool.isort]
#import_heading_firstparty = "First-party"
#import_heading_localfolder = "Local"
#import_heading_stdlib = "Standard library"
#import_heading_thirdparty = "Third-party"
line_length = 88
multi_line_output = 3
profile = 'black'
skip_glob = [
    '*/migrations/*',
]
