name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: cc_licenses.settings.deploy
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      # https://github.com/actions/checkout
    - uses: actions/checkout@v2

      # https://github.com/actions/setup-python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Generate secret key
      run: |
        echo secret_key=$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM >> $GITHUB_ENV
        echo ${{ env.secret_key }}

    - name: Load database schema
      env:
        DJANGO_SECRET_KEY: ${{ env.secret_key }}
      run: |
        pipenv run ./manage.py migrate

    - name: Start development server
      env:
        DJANGO_SECRET_KEY: ${{ env.secret_key }}
      run: |
        pipenv run ./manage.py runserver

    # https://github.com/pre-commit/action
    - uses: pre-commit/action@v2.0.0
      env:
        DJANGO_SECRET_KEY: ${{ env.secret_key }}
