# Remember to also update the Docker Compose configuration, as appropriate:
#   cc-legal-tools-app/docker-compose.yml

name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    env:
      DATA_REPOSITORY_DIR: cc-legal-tools-data
      DJANGO_SETTINGS_MODULE: cc_legal_tools.settings.ephemeral

    steps:

    # https://github.com/actions/checkout
    - name: Checkout cc-legal-tools-app
      uses: actions/checkout@v2

    # https://github.com/actions/checkout
    - name: Checkout cc-legal-tools-data
      uses: actions/checkout@v2
      with:
        repository: creativecommons/cc-legal-tools-data
        path: cc-legal-tools-data

    - name: Configure testing git identity
      run: |
        git config --global user.email "testing_user@localhost"
        git config --global user.name "Testing User"

    # https://github.com/actions/setup-python
    - name: actions/setup-python@v2 Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Install Python dependencies
      run: |
        pipenv sync --dev

    - name: Update Django database schema
      run: |
        pipenv run ./manage.py migrate

    - name: Start Django development web server
      run: |
        pipenv run ./manage.py runserver &>/dev/null &

    # https://github.com/pre-commit/action
    - uses: pre-commit/action@v2.0.3
